default:
  image: openjdk:18
  tags:
    - ILT

variables:
  GIT_STRATEGY: clone
  GIT_FETCH_EXTRA_FLAGS: --tags

before_script:
  - export GRADLE_USER_HOME="$(pwd)/.gradle"

stages:
  - setup
  - build
  - release

setup_job:
  stage: setup
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - ./gradlew createRelease -Prelease.disableChecks
    - echo "TAG=$(./gradlew currentVersion -q -Prelease.quiet)" >> variables.env
  artifacts:
    reports:
      dotenv: variables.env

build_job:
  stage: build
  before_script:
    - echo GE_JOB_ID=$CI_JOB_ID >> build.env
  script:
    - ./gradlew build
  artifacts:
    paths:
      - build/libs/
    reports:
      dotenv: build.env

release_job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: setup_job
      artifacts: true
    - job: build_job
      artifacts: true
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - echo "releasing v$TAG"
  release:
    name: 'Release v$TAG'
    description: $CI_COMMIT_MESSAGE
    tag_name: v$TAG
    assets:
      links:
        - name: 'Executable jar'
          url: 'https://gitlab-ext.iosb.fraunhofer.de/ilt-pse/ss22-vorhersagenverwaltung-mit-der-sensorthings-api/vorhersagenverwaltungsta_backend/-/jobs/${GE_JOB_ID}/artifacts/build/libs/VorhersagenverwaltungSTA-$TAG-SNAPSHOT.jar'