default:
  image: openjdk:18

variables:
  GIT_STRATEGY: clone
  GIT_FETCH_EXTRA_FLAGS: --tags
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - build
  - publish
  - release

build_job:
  stage: build
  script:
    - ./gradlew build

publish_job:
  stage: publish
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - ./gradlew createRelease -Prelease.disableChecks
    - echo "TAG=$(./gradlew currentVersion -q -Prelease.quiet)" >> variables.env
  artifacts:
    reports:
      dotenv: variables.env

release_job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: publish_job
      artifacts: true
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - echo "Releasing $TAG"
  release:
    name: 'Release v$TAG'
    description: $CI_COMMIT_MESSAGE
    tag_name: v$TAG
    ref: $CI_COMMIT_SHA